name: CI

on: [push, pull_request]

defaults:
    run:
        shell: bash

jobs:
    build_and_test:
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]

        name: ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: Build and Install
              run: ./install.py

            - name: Check
              run: deus help